/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import Controllers.Client;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import mdlaf.MaterialLookAndFeel;
import mdlaf.animation.MaterialUIMovement;
import mdlaf.utils.MaterialColors;

/**
 *
 * @author Shehan
 */
public class Login extends javax.swing.JFrame implements Runnable {

    public static boolean loggedIn = false;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        signInButton.setEnabled(false);
       
        Thread t1 = new Thread(this);
        t1.start();
    }

    @Override
    public void run() {
        Client tclient = new Client();
        while (true) {
            jLabel1.setText("trying to reach server...");
            if (!tclient.checkAuthenticationServer()) {
                signInButton.setEnabled(false);
                jLabel1.setText("Please check your connection.");

                try {   //Try again in 5s
                    Thread.sleep(5000);
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }
            } else {
                jLabel1.setText("");
                signInButton.setEnabled(true);
                
                 try {   //sleep for 30s
                    Thread.sleep(30000);
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        usernameInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();
        label2 = new java.awt.Label();
        jPanel6 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        signInButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(48, 48, 48));
        jPanel5.setBackground(MaterialColors.BLUE_GRAY_900);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameInput.setBackground(jPanel5.getBackground());
        usernameInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernameInput.setForeground(new java.awt.Color(255, 255, 255));
        usernameInput.setToolTipText("");
        usernameInput.setBorder(null);
        usernameInput.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameInput.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        usernameInput.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        usernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputActionPerformed(evt);
            }
        });
        jPanel5.add(usernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 222, 210, 22));

        passwordInput.setBackground(jPanel5.getBackground());
        passwordInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordInput.setForeground(new java.awt.Color(255, 255, 255));
        passwordInput.setBorder(null);
        passwordInput.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        passwordInput.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });
        jPanel5.add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 209, 20));

        label2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Sign In");
        jPanel5.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 69, 135, 48));

        jPanel6.setBackground(new java.awt.Color(100, 181, 246));
        jPanel6.setBackground(MaterialColors.LIGHT_BLUE_400);
        jPanel6.setMinimumSize(new java.awt.Dimension(135, 48));
        jPanel6.setPreferredSize(new java.awt.Dimension(135, 48));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 136, 10));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 210, 20));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 245, 210, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password_icon.png"))); // NOI18N
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 52, 40));

        signInButton.setBackground(new java.awt.Color(25, 118, 210));
        signInButton.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        signInButton.setForeground(new java.awt.Color(255, 255, 255));
        signInButton.setText("Sign In");
        signInButton.setBorder(null);
        signInButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        signInButton.setBackground (MaterialColors.BLUE_800);
        signInButton.setForeground (Color.WHITE);
        signInButton.addMouseListener(MaterialUIMovement.getMovement(signInButton, MaterialColors.INDIGO_900));
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });
        jPanel5.add(signInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 290, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/username_icon.png"))); // NOI18N
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 50));

        closeButton.setBackground(new java.awt.Color(48, 48, 48));
        closeButton.setForeground(new java.awt.Color(48, 48, 48));
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cross_icon.png"))); // NOI18N
        closeButton.setToolTipText("");
        closeButton.setBorder(null);
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setBackground (MaterialColors.BLUE_GRAY_900);

        closeButton.addMouseListener(MaterialUIMovement.getMovement(closeButton, MaterialColors.GRAY_900));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        jPanel5.add(closeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 40, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 290, 20));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
        signInButtonActionPerformed(evt);
    }//GEN-LAST:event_passwordInputActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void usernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputActionPerformed
        signInButtonActionPerformed(evt);
    }//GEN-LAST:event_usernameInputActionPerformed

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed

        String username = usernameInput.getText();
        String password = new String(passwordInput.getPassword());
        Client client = new Client();

        if (client.login(username, password)) {
            for (float i = 1.0f; i > 0.0f; i -= 0.2f) { //Fade out effect
                this.setOpacity(i);
                try {
                    Thread.sleep(30);
                } catch (Exception ignored) {
                }
            }
            loggedIn = true;
            this.setVisible(false);
            MainPage mainPage = new MainPage();
            mainPage.setVisible(true);
        } else {
            loggedIn = false;
            Alert alert = new Alert("Incorrect username/Password");
        }
    }//GEN-LAST:event_signInButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel(new MaterialLookAndFeel());
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.Label label2;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JButton signInButton;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
